name: SDK_Integration
description: BS Fintech Pvt Ltd

publish_to: 'none'

version: 4.3.6+83

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true